name: artistmagnet
description: "Artistmagnet"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  video_player: ^2.9.2
  get: ^4.7.2
  smooth_page_indicator: ^1.2.0+3
  flutter_svg: ^2.0.16
  get_cli: ^1.9.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: MyriadPro
      fonts:
        - asset: assets/fonts/MyriadPro-Bold.otf
        - asset: assets/fonts/MyriadPro-Light.otf
        - asset: assets/fonts/MyriadPro-Regular.otf
        - asset: assets/fonts/MyriadPro-SemiBold.otf

